name: pdflatex resume
on: [push]
jobs:
  latex-resume:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: "actions/checkout@v4"
      - name: latex install
        run: "sudo apt update && sudo apt install -y texlive-latex-base  texlive-fonts-recommended texlive-fonts-extra"
      - name: latex build
        run: pdflatex resume.tex
      - name: latex format
        run: |
          curl -LO https://github.com/cmhughes/latexindent.pl/releases/download/V3.23.2/latexindent-linux
          chmod u+x latexindent-linux
          ./latexindent-linux resume.tex >resume-indented.tex
          mv resume-indented.tex resume.tex
          git config --global user.email "eldondevat-rgha@eldondev.com"
          git config --global user.name "Eldonbot"
          git diff |grep . >/dev/null && git commit -m "Fix indents" resume.tex
          git push
          git checkout -B result HEAD
          git add resume.pdf
          git commit -m "Committing pdf on branch"
          git push -fu origin HEAD

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: |
            resume.pdf
