name: pdflatex resume
on: [push]
jobs:
  latex-resume:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: "actions/checkout@v4"
      - name: latex install
        run: "sudo apt update && sudo apt install -y texlive-latex-base  texlive-fonts-recommended texlive-fonts-extra"
      - name: latex build
        run: pdflatex resume.tex
      - name: latex format
        run: |
          git checkout -B result HEAD
          cp -iv resume.pdf ${GITHUB_SHA}.pdf
          git add ${GITHUB_SHA}.pdf resume.pdf
          git commit -m "Committing pdf on branch"
          git push -u origin HEAD

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: |
            resume.pdf
